---
language: python

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

before_script:
  # Extracting variables for collection
  - COLLECTION_NAMESPACE=`grep 'namespace:' galaxy.yml | tail -n1 | awk '{ print $2}' | tr -d \"`
  - COLLECTION_NAME=`grep 'name:' galaxy.yml | tail -n1 | awk '{ print $2}' | tr -d \"`
  - VERSION=`grep 'version:' galaxy.yml | tail -n1 | awk '{ print $2}' | tr -d \"`

deploy:
  provider: script
  script: bash deploy.sh
  on:
    tags: true
    branch: master