---
language: python

env:
  global:
    - COLLECTION_NAMESPACE: carceneaux
    - COLLECTION_NAME: test

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

before_script:
  # Move the roles into another folder to eliminate excess files
  - ROLES=`find -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*' -printf '%f\n'`
  - mkdir collection
  - for r in $ROLES; do cp -Rp "$r" collection; done
  - cp galaxy.yml collection/
  - cp README.md collection/
  - cp LICENSE collection/
  - cd collection/

script:
  - ansible-galaxy collection build
  - ansible-galaxy collection publish ./$COLLECTION_NAMESPACE-$COLLECTION_NAME-1.0.0.tar.gz --api-key $ANSIBLE_GALAXY_TOKEN