---
language: python

env:
  global:
    - COLLECTION_NAMESPACE: carceneaux
    - COLLECTION_NAME: test

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

deploy:
  provider: script
  script: ansible-playbook -i 'localhost,' deploy.yml -e "tag=$TRAVIS_TAG"
  'on':
    tags: true