---
language: python

env:
  global:
    - COLLECTION_NAMESPACE: carceneaux
    - COLLECTION_NAME: test

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

before_script:
  # Move the collection into the required path to make ansible-test work.
  - ROLES=`find -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*' -printf '%f\n'`
  - mkdir -p $COLLECTION_NAMESPACE/$COLLECTION_NAME
  - foreach r ( $ROLES ); cp -Rp $n $COLLECTION_NAMESPACE/$COLLECTION_NAME; end
  - ls $COLLECTION_NAMESPACE/$COLLECTION_NAME

# deploy:
#   provider: script
#   script: ansible-playbook -i 'localhost,' deploy.yml -e "tag=$TRAVIS_TAG"
#   'on':
#     tags: true