---
language: python

# require the branch name to be master (note for PRs this is the base branch name)
if: branch = test

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

before_script:
  # Extracting variables for collection
  - COLLECTION_NAMESPACE=`grep 'namespace:' galaxy.yml | tail -n1 | awk '{ print $2}' | tr -d \"`
  - COLLECTION_NAME=`grep 'name:' galaxy.yml | tail -n1 | awk '{ print $2}' | tr -d \"`
  - VERSION=`grep 'version:' galaxy.yml | tail -n1 | awk '{ print $2}' | tr -d \"`

script:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then echo "$COLLECTION_NAMESPACE-$COLLECTION_NAME-$VERSION.tar.gz"; fi
  # - ansible-galaxy collection build
  # - ansible-galaxy collection publish ./$COLLECTION_NAMESPACE-$COLLECTION_NAME-$VERSION.tar.gz --api-key $ANSIBLE_GALAXY_TOKEN